server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/users_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-circular-references: true
    #    web-application-type :  reactive
    allow-bean-definition-overriding: true

  secret:
    key: # insert secret key here

  accessible:
    endpoints: /api/v1/user/addUser


  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter
 

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
